alias ls='ls --color=auto'
alias ll='ls -la'
alias l.='ls -d .*'
alias grep='grep --color=auto'
alias ip='ip --color=auto'
alias mkdir='mkdir -pv'
alias amnesia='sudo bleachbit -c --preset; bleachbit -c --preset'
alias windows='sudo grub-reboot 1 && sudo reboot'
alias btw='neofetch --disable host cpu gpu'
alias yeet='yay -Rcns'
alias yeetnt='yay -Runs'
alias yorphan='yay -Qdtq | yay -Rns -'
alias yircular='yay -Qqd | yay -Rsu --print -'
alias dlna='minidlnad -f /home/nailer/.config/minidlna/minidlna.conf -P /home/nailer/.config/minidlna/minidlna.pid -d'
alias kquit='qdbus6 org.kde.Shutdown /Shutdown  org.kde.Shutdown.logout'
alias vmic='pactl load-module module-remap-source master=alsa_output.pci-0000_00_1b.0.analog-stereo.monitor source_name=virtmic source_properties=device.description=Virtual_Microphone'
